# Set the base image to Python 3.7
FROM python:3.7-slim-buster

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the requirements
RUN pip install -r requirements.txt

# Copy the rest of the application
COPY . .

# Run the application
CMD ["python","run.py"]
