"""initialize

Revision ID: 46babf90ddb3
Revises: 
Create Date: 2022-03-12 14:49:53.636951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46babf90ddb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('udemy_courselist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('link', sa.String(length=250), nullable=False),
    sa.Column('searchcount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_syllabus', sa.Text(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('udemy_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['udemy_course_id'], ['udemy_courselist.id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('udemy_courselist')
    # ### end Alembic commands ###
