"""new

Revision ID: b4e9625faae1
Revises: 
Create Date: 2021-11-02 20:03:03.880451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e9625faae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_name', sa.String(length=80), nullable=False),
    sa.Column('course_link', sa.String(length=250), nullable=False),
    sa.Column('course_syllabus', sa.Text(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('course_link'),
    sa.UniqueConstraint('course_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
