"""new

Revision ID: d9d140eda0a8
Revises: 
Create Date: 2021-10-19 16:28:21.352477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d140eda0a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursecontent',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=80), nullable=False),
    sa.Column('course_link', sa.String(length=250), nullable=False),
    sa.Column('course_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coursecontent')
    # ### end Alembic commands ###
