"""new

Revision ID: e56184360866
Revises: 
Create Date: 2021-10-24 16:27:04.064621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56184360866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=80), nullable=False),
    sa.Column('course_link', sa.String(length=250), nullable=False),
    sa.Column('course_syllabus', sa.Text(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
